server:
  port: 8083

spring:
  application:
    name: springcloud-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    first:
      initial-size: 1
      max-active: 5
    password: root
    url: jdbc:mysql://localhost:3306/root
    username: root
  jpa:
    database: mysql

  data:
    mongodb:
      uri: mongodb://localhost:27017/1809awang

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    pool:
    max-active: 20
    max-wait: -1
    max-idle: 8
    min-idle: 0

mybatis:
  mapper-locations: classpath*:mapper/*.xml


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

